language: c

install:
  - sudo apt-get update -qq
  - sudo apt-get install -y -qq lcov curl

script:
  - mkdir build-release && cd build-release
  - cmake -DCMAKE_BUILD_TYPE=Release ..
  - make
  - make test
  - cd ..
  - mkdir build-debug && cd build-debug
  - cmake -DCOVERALLS=ON -DCMAKE_BUILD_TYPE=Debug .. 
  - make
  - make test
  - make coveralls
  - cat coveralls.json
